### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by brainfoolong** [brainfoolong/web-ftp-client#1]
Here is the official todolist that what is planned. For new ideas open new issues.

- [x] Translation to german
- [ ] Timed Jobs - Transfer from server x, some files y at given time z
- [ ] Goto beta phase when enough feedback is in

**Comment by AdrianKoshka** [comment]
I know this is an `ftp` client, but does it (or could it) have `sftp` support?

**Comment by brainfoolong** [comment]
It already has. I should mention that somewhere :)

**Comment by AdrianKoshka** [comment]
Thanks!Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [brainfoolong/web-ftp-client] Roadmap (#1)From: Roland Eigelsreiter To: brainfoolong/web-ftp-client CC: Theodore Seán Tubbs ,Comment It already has. I should mention that somewhere :)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brainfoolong/web-ftp-client","title":"brainfoolong/web-ftp-client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/brainfoolong/web-ftp-client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brainfoolong in #1: It already has. I should mention that somewhere :)"}],"action":{"name":"View Issue","url":"https://github.com/brainfoolong/web-ftp-client/issues/1#issuecomment-292069167"}}}

**Comment by AdrianKoshka** [comment]
Thanks!
